[package]
name = "serum-stake"
version = "0.1.0"
description = "Serum staking pool"
repository = "https://github.com/project-serum/serum-dex"
edition = "2018"

[features]
program = ["borsh/serum-program", "solana-client-gen/program", "spl-token/program", "serum-common/program", "serum-pool-schema/program"]
client = ["borsh/serum-client", "solana-client-gen/client", "spl-token/default", "serum-common/client", "serum-pool-schema/default"]
test = []
strict = []
default = []

[dependencies]
solana-sdk = { version = "1.3.14", default-features = false }
spl-token = { version = "2.0.6", default-features = false }
num_enum = "0.5.0"
thiserror = "1.0.20"
solana-client-gen = { path = "../../solana-client-gen" }
serum-common = { path = "../../common" }
bytemuck = "1.4.0"
arrayref = "0.3.6"
serum-pool-schema = { path = "../../pool/schema", default-features = false }

# Forks.
borsh = { git = "https://github.com/project-serum/borsh", branch = "serum" }
