[package]
name = "serum-wl-program"
version = "0.1.0"
description = "Serum Wl Solana program"
repository = "https://github.com/project-serum/serum-dex"
edition = "2018"

[workspace]

[lib]
crate-type = ["cdylib", "lib"]
name = "serum_wl_program"

[features]
program = ["solana-sdk/program", "spl-token/program", "spl-token/no-entrypoint", "serum-common/program"]
client = ["solana-sdk/default", "spl-token/default", "serum-common/client", "lazy_static"]
strict = []
default = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
solana-sdk = { version = "1.3.14", default-features = false }
spl-token = { version = "2.0.6", default-features = false }
serum-common = { path = "../../common" }
solana-client-gen = { path = "../../solana-client-gen" }
bytemuck = "1.4.0"
thiserror = "1.0.20"
lazy_static = { version = "1.4.0", optional = true }

[profile.release]
lto = true

[profile.test]
opt-level = 2
