include ../Makefile

LIB_NAME=serum_wl_program

.PHONY: buil% deploy

#
# Override the following targets since there's no client to build.
#

buil%:
	@make build-program-super

deploy: buil%
	@make deploy-super
