[package]
name = "serum-safe"
version = "0.1.0"
description = "Serum Safe"
repository = "https://github.com/project-serum/serum-dex"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "serum_safe"

[features]
program = ["solana-sdk/program", "serum-safe-interface/program"]
test = ["solana-sdk/default"]
default = []

[dependencies]
solana-sdk = { version = "=1.3.9", default-features = false, features = ["program"] }
bincode = "1.3.1"
num_enum = "0.5.0"
thiserror = "1.0.20"
serum-safe-interface = { path = "./interface" }

[profile.release]
lto = true

[profile.test]
opt-level = 2
