[package]
name = "serum-safe-program"
version = "0.1.0"
description = "Serum Safe"
repository = "https://github.com/project-serum/serum-dex"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "serum_safe_program"

[features]
program = ["serum-safe/program", "solana-sdk/program", "spl-token/program"]
test = ["solana-sdk/default"]
default = []

[dependencies]
solana-sdk = { version = "=1.3.9", default-features = false, features = ["program"] }
bincode = "1.3.1"
num_enum = "0.5.0"
thiserror = "1.0.20"
serum-safe = { path = "../" }
spl-token = { version = "=2.0.3", default-features = false }
arrayref = "0.3.6"

[profile.release]
lto = true

[profile.test]
opt-level = 2
