[package]
name = "serum-safe-program"
version = "0.1.0"
description = "Serum Safe"
repository = "https://github.com/project-serum/serum-dex"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "serum_safe_program"

[features]
program = ["serum-safe/program", "solana-sdk/program", "spl-token/program", "spl-token/no-entrypoint"]
test = ["solana-sdk/default"]
strict = []
default = []

[dependencies]
solana-sdk = { version = "=1.3.9", default-features = false }
spl-token = { version = "=2.0.3", default-features = false }
serum-safe = { path = "../" }
arrayref = "0.3.6"
safe-transmute = "0.11.0"
bincode = "1.3.1"

[profile.release]
lto = true

[profile.test]
opt-level = 2
