[package]
name = "serum-rewards-constant"
version = "0.1.0"
description = "Serum Rewards Constant Solana program"
repository = "https://github.com/project-serum/serum-dex"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "serum_rewards_constant"

[features]
program = ["solana-sdk/program"]
strict = []


[dependencies]
solana-sdk = { version = "=1.3.9", default-features = false }
serum-common = { path = "../../common", features = ["program"] }
num_enum = "0.5.0"
thiserror = "1.0.20"

[profile.release]
lto = true

[profile.test]
opt-level = 2
