[package]
name = "serum-safe-interface"
version = "0.1.0"
authors = ["armaniferrante <armaniferrante@gmail.com>"]
edition = "2018"

[features]
program = ["solana-client-gen/program"]
client = ["solana-client-gen/client"]
default = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
solana-client-gen = { path = "../../../solana-client-gen"}