[package]
name = "serum-registry-program"
version = "0.1.0"
description = "Serum Registry Solana program"
repository = "https://github.com/project-serum/serum-dex"
edition = "2018"

[workspace]

[lib]
crate-type = ["cdylib"]
name = "serum_registry_program"

[features]
program = ["serum-registry/program", "solana-sdk/program", "spl-token/program", "spl-token/no-entrypoint"]
strict = []
default = []

[dependencies]
solana-sdk = { version = "1.3.14", default-features = false }
spl-token = { version = "2.0.6", default-features = false }
serum-registry = { path = "../" }
serum-common = { path = "../../common", features = ["program"] }
serum-stake = { path = "../stake", features = ["program"] }
serum-lockup = { path = "../../lockup", features = ["program"] }
serum-pool-schema = { path = "../../pool/schema", default-features = false, features = ["program"] }
solana-program = "1.4.3"
arrayref = "0.3.6"
borsh = { git = "https://github.com/project-serum/borsh", branch = "serum" }

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
opt-level = 'z'

[profile.test]
opt-level = 2
