[package]
name = "serum-safe"
version = "0.1.0"
authors = ["armaniferrante <armaniferrante@gmail.com>"]
edition = "2018"

[features]
program = ["solana-client-gen/program"]
client = ["solana-client-gen/client"]
test = ["rand", "solana-sdk", "solana-sdk/default", "solana-transaction-status", "solana-client-gen/client", "solana-client", "serum-common"]
default = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
solana-client-gen = { path = "../solana-client-gen" }

# Used for testing.
rand = { version = "0.7.3", optional = true }
solana-sdk = { version = "=1.3.9", default-features = false, optional = true }
solana-transaction-status = { version = "1.3.9", optional = true }
solana-client = { version = "1.3.4", optional = true }
serum-common = { path = "../common", optional = true }