[package]
name = "serum-safe"
version = "0.1.0"
authors = ["armaniferrante <armaniferrante@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
structopt = "0.3"
solana-sdk = "1.3.4"
solana-client = "1.3.4"
serum-common = { path = "../../common" }
serum-safe-interface = { path = "../../safe/program/interface", features = ["client"] }
