[package]
name = "serum-safe-cli"
version = "0.1.0"
authors = ["armaniferrante <armaniferrante@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
structopt = "0.3"
solana-sdk = "1.3.4"
solana-client = "1.3.4"
serum-common-client = { path = "../../common/client" }
serum-safe = { path = "../", features = ["client"] }
