PROGRAM_ID=Gz3tD6ob83ZTFnGEd2ERzQ1nvDEL5vsXm7E43G9uCaCE
PAYER_FILEPATH=~/.config/solana/id.json
CLUSTER=l

default:
	cargo run -- \
		--program-id $(PROGRAM_ID) \
		--payer-filepath $(PAYER_FILEPATH) \
		--cluster $(CLUSTER) \
		$(cmd)
