[package]
name = "serum-common-client"
version = "0.1.0"
authors = ["armaniferrante <armaniferrante@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
rand = "0.7.3"
solana-client = "1.3.4"
solana-sdk = "1.3.4"
spl-token = { version = "=2.0.3", default-features = false }